"""
Dedicated image-generation backend for image-only models.

Some models registered in ``llm_config`` (e.g. OpenRouter's
``inclusionai/ming-image-0.1-design``) are *text-to-image* models: they can only
be called through a provider's dedicated images endpoint and reject the
``chat/completions`` endpoint with a 404 ("... is an image generation model and
cannot be used with the chat/completions endpoint. Use the /api/v1/images
endpoint instead.").

``route_llm_call`` diverts models flagged ``image_output=1 / text_output=0`` to
``generate_image_llm`` here instead of the chat-based provider loops. The
function mirrors the signature of the ``call_*_llm`` providers so the router can
dispatch to it transparently, reusing the same feedback/usage/retry helpers.

The generated image is saved under ``files/temp/`` (already served by the
``/api/temp/<filename>`` route) and the returned string is a Markdown image tag
that the web chat / IDE render natively; the WhatsApp webhook converts it into a
native media message.
"""

import base64
import logging
import os
import uuid

import requests

from agent.db_feedback import insert_feedback
from agent.openai_tools import (
    _API_CALL_MAX_RETRIES,
    _PROVIDER_BALANCE_WAIT,
    _is_provider_balance_error,
    _is_rate_limit_error,
    _wait_seconds_for_rate_limit,
)
from agent.stop_check import StopRequestedError, sleep_interruptible
from utils.file_utils import download_file, get_temp_file_path

logger = logging.getLogger(__name__)

# OpenRouter dedicated image-generation endpoint (NOT chat/completions).
_OPENROUTER_IMAGES_URL = "https://openrouter.ai/api/v1/images"
# Headers OpenRouter uses for ranking/attribution, mirroring call_openrouter_llm.
_OPENROUTER_HEADERS = {
    "HTTP-Referer": "https://github.com/nanoworker",
    "X-OpenRouter-Title": "NanoWorker",
}
# Long enough for slow image models but bounded so a hung provider does not
# block the worker forever.
_REQUEST_TIMEOUT = 300
# Safety cap on the prompt length sent to the model.
_MAX_PROMPT_CHARS = 4000
# media_type -> file extension (for saving the generated bytes).
_MEDIA_TYPE_EXT = {
    "image/png": "png",
    "image/jpeg": "jpg",
    "image/jpg": "jpg",
    "image/webp": "webp",
    "image/svg+xml": "svg",
}


def _content_to_prompt(content) -> str:
    """
    Extracts a plain-text prompt from the enriched message ``content``.

    ``content`` may be a plain string or a list of Gemini ``types.Part`` (with
    ``.text``) / plain strings. Non-text parts are ignored. The result is
    trimmed to ``_MAX_PROMPT_CHARS``.
    """
    parts = []
    if isinstance(content, list):
        for p in content:
            if isinstance(p, str):
                if p.strip():
                    parts.append(p)
            else:
                text = getattr(p, "text", None)
                if text and text.strip():
                    parts.append(text)
    elif isinstance(content, str):
        parts.append(content)
    else:
        text = getattr(content, "text", None)
        if text and text.strip():
            parts.append(text)
        elif content:
            parts.append(str(content))

    prompt = "\n".join(parts).strip()
    if len(prompt) > _MAX_PROMPT_CHARS:
        prompt = prompt[:_MAX_PROMPT_CHARS]
    return prompt


def _ext_for_media_type(media_type: str) -> str:
    """Maps a media_type (e.g. ``image/png``) to a file extension."""
    if not media_type:
        return "png"
    return _MEDIA_TYPE_EXT.get(media_type.strip().lower(), "png")


def _save_image_bytes(data_b64: str, media_type: str) -> str:
    """
    Decodes base64 image data and writes it to a temp file under
    ``files/temp/``. Returns the basename (served by ``/api/temp/<basename>``).
    """
    raw = base64.b64decode(data_b64)
    ext = _ext_for_media_type(media_type)
    out_path = get_temp_file_path(f"gen_{uuid.uuid4().hex[:8]}.{ext}")
    with open(out_path, "wb") as f:
        f.write(raw)
    return os.path.basename(out_path)


def _download_to_temp(url: str, media_type: str) -> str:
    """Downloads an image URL into ``files/temp/`` and returns its basename."""
    ext = _ext_for_media_type(media_type)
    out_path = get_temp_file_path(f"gen_{uuid.uuid4().hex[:8]}.{ext}")
    download_file(url, out_path)
    return os.path.basename(out_path)


def _log_usage(session_id, message_in_id, model_name, usage):
    """Fail-safe usage logging (image models report completion/prompt tokens)."""
    try:
        from agent.llm_usage import log_llm_usage

        if not usage or not isinstance(usage, dict):
            return
        usage_in = int(usage.get("prompt_tokens") or 0)
        usage_out = int(usage.get("completion_tokens") or 0)
        if usage_in or usage_out:
            log_llm_usage(
                session_id, message_in_id, "legacy", model_name, usage_in, usage_out
            )
    except Exception:
        pass


def _emit_feedback(cursor, table, session_id, message_in_id, message, on_complete):
    """Inserts a feedback row and fires the real-time callback (best effort)."""
    try:
        insert_feedback(cursor, table, session_id, message_in_id, message)
    except Exception:
        pass
    if on_complete:
        try:
            on_complete(message)
        except Exception as e:
            logger.warning(f"on_complete failed for image feedback: {e}")


def generate_image_llm(
    model_name: str,
    history: list,
    config_kwargs: dict,
    content,
    cursor,
    session_id: str,
    message_in_id: str,
    table: str,
    api_key: str = None,
    max_output_tokens: int = None,
    on_complete=None,
) -> str:
    """
    Generates an image for an image-only model via OpenRouter's images endpoint.

    Mirrors the signature of the ``call_*_llm`` providers so ``route_llm_call``
    can dispatch to it transparently (including from the fallback chain).

    Returns a Markdown image tag string that the web chat / IDE render natively
    and the WhatsApp webhook converts to a native media message. Raises on
    unrecoverable errors so the model fallback chain can take over.
    """
    if not api_key:
        raise ValueError("API Key for OpenRouter model is not set.")

    # Strip an "openrouter/" prefix (chat models keep it, image slugs don't).
    actual_model = (
        model_name[len("openrouter/") :]
        if model_name.lower().startswith("openrouter/")
        else model_name
    )

    prompt = _content_to_prompt(content)
    if not prompt:
        raise ValueError(
            "Could not extract a text prompt for image generation from the message."
        )

    headers = {
        "Authorization": f"Bearer {api_key}",
        "Content-Type": "application/json",
        **_OPENROUTER_HEADERS,
    }
    payload = {"model": actual_model, "prompt": prompt}

    _emit_feedback(
        cursor,
        table,
        session_id,
        message_in_id,
        "Gerando imagem...",
        on_complete,
    )

    last_exc = None
    body = None
    for attempt in range(_API_CALL_MAX_RETRIES):
        try:
            response = requests.post(
                _OPENROUTER_IMAGES_URL,
                headers=headers,
                json=payload,
                timeout=_REQUEST_TIMEOUT,
            )
            response.raise_for_status()
            body = response.json()
            break
        except Exception as e:
            last_exc = e
            if _is_provider_balance_error(e):
                if attempt >= _API_CALL_MAX_RETRIES - 1:
                    raise
                wait_seconds = _PROVIDER_BALANCE_WAIT
                feedback = (
                    f"💳 Model provider temporarily unavailable (402, insufficient "
                    f"balance) on attempt {attempt + 1}/{_API_CALL_MAX_RETRIES}. "
                    f"Waiting {wait_seconds:.0f}s to retry..."
                )
            elif _is_rate_limit_error(e):
                if attempt >= _API_CALL_MAX_RETRIES - 1:
                    raise
                wait_seconds = _wait_seconds_for_rate_limit(e)
                feedback = (
                    f"⏳ Rate limit (429) on attempt {attempt + 1}/"
                    f"{_API_CALL_MAX_RETRIES}. Waiting {wait_seconds:.0f}s to retry..."
                )
            else:
                raise

            _emit_feedback(
                cursor, table, session_id, message_in_id, feedback, on_complete
            )
            if sleep_interruptible(wait_seconds):
                raise StopRequestedError(
                    "Stopped while waiting to retry image generation."
                )
    else:  # pragma: no cover - loop always breaks or raises
        raise last_exc

    data = body.get("data") if isinstance(body, dict) else None
    if not data or not isinstance(data, list) or not data:
        raise ValueError("Image generation returned no data.")

    item = data[0]
    media_type = item.get("media_type") or "image/png"
    basename = None
    if item.get("b64_json"):
        basename = _save_image_bytes(item["b64_json"], media_type)
    elif item.get("url"):
        basename = _download_to_temp(item["url"], media_type)

    if not basename:
        raise ValueError("Image generation response contained no image data.")

    _log_usage(session_id, message_in_id, model_name, body.get("usage"))

    # Return only the Markdown image tag: the short "Gerando imagem..."
    # acknowledgment was already streamed as feedback above, and the web chat /
    # IDE render this natively while the WhatsApp webhook delivers it as a
    # native media message with no caption.
    return f"![imagem gerada](/api/temp/{basename})"

